2015-07-01 11:13:26,114 ERROR exception
Traceback (most recent call last):
  File "D:\Development\eclipse-jee-with-android_workspace\RemoteCreditSystem\RemoteCreditSystem\views\system\rcs_user.py", line 49, in new_user
    UserRole(user.id,request.form['roles']).add()
  File "D:\Development\eclipse-jee-with-android_workspace\RemoteCreditSystem\virtualenv32\lib\site-packages\werkzeug\datastructures.py", line 391, in __getitem__
    raise exceptions.BadRequestKeyError(key)
BadRequestKeyError: 400: Bad Request
2015-07-01 11:15:51,319 ERROR exception
Traceback (most recent call last):
  File "D:\Development\eclipse-jee-with-android_workspace\RemoteCreditSystem\RemoteCreditSystem\views\system\rcs_user.py", line 49, in new_user
    UserRole(user.id,request.form['roles']).add()
  File "D:\Development\eclipse-jee-with-android_workspace\RemoteCreditSystem\virtualenv32\lib\site-packages\werkzeug\datastructures.py", line 391, in __getitem__
    raise exceptions.BadRequestKeyError(key)
BadRequestKeyError: 400: Bad Request
